- name: Get API info with Ansible
  hosts: fry
  tasks:
  - name: Download content
    get_url:
      url: http://api.open-notify.org/
      dest: ~/astros.html

  - name: Return content
    uri:
      url: http://api.open-notify.org/astros.json
      return_content: True
    register: uri_info

  - name: debug uri_info
    debug:
      var: uri_info.json

