---
- name: Our first play
  hosts: planetexpress
  gather_facts: yes # runs by default

  tasks:
  - name: debug os type
    debug:
      var: ansible_distribution

  - name: debug msg
    debug:
      msg: Apt will work here!
    when: ansible_distribution == "Ubuntu"

  - name: debug msg
    debug:
      msg: Apt will not work here! :[
    when: ansible_distribution != "Ubuntu"
